package:
  name: roq-redis-adapter
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: True  # [win and osx]
  number: {{ GIT_DESCRIBE_NUMBER }}
  run_exports:
    - {{ pin_subpackage('roq-redis-adapter', max_pin='x.x.x') }}
  script_env:                                                                                                              
    - ROQ_BUILD_TYPE

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - roq-client
    - roq-io
    - roq-oss-abseil-cpp
    - roq-oss-catch2
    - roq-oss-range-v3
    - libhiredis

about:
  home: https://roq-trading.com
  doc_url: https://roq-trading.com/docs
  dev_url: https://github.com/roq-trading
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Roq Redis Adapter
